title: Klise Theme
description: >-
  He's writing in Bahasa about web technology and experience as a journal  for
  documentation things that he learned, meet him <a
  href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: 'https://github.com/piharpi/jekyll-klise'
mode: dark
author:
  name: Henri Takeda Boteon
  bio: >-
    Second-year Chemical and Biological Engineering student at UBC, Vancouver. Find me on <break>
    <a
    href="https://twitter.com/pistachihoni" target="_blank"
    rel="noopener">@twitter</a>, <a
    href="https://www.instagram.com/henri.boteon/" target="_blank"
    rel="noopener">@instagram</a>, <a
    href="https://discordapp.com/users/788123099748630567" target="_blank"
    rel="noopener">discord</a>

  username: pistachi
  github: pistachihen
  twitter: pistachihoni
  email: henriboteon@gmail.com
  avatar: https://imgur.com/75b63152-a63c-4e42-84c2-af51568f8416
url: ''
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
