title: Pistachis website
description: >-
  This blog is for documentation on my thoughts, services and randoms.
lang: en-US
timezone: Pacific
image: assets/img/ogp.png
repo: 'https://github.com/Pistachihen/pistachi.github.io'
mode: dark
author:
  name:
  bio: >-
    Second-year Chemical and Biological Engineering student at UBC, Vancouver.
    
  username: pistachi
  github: pistachihen
  twitter: pistachihoni
  email: henriboteon@gmail.com
  avatar: https://i.imgur.com/G4cMDhr.png
url: ''
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
